# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a46635f44e35f5b840bd7f3457d06d4c1b5c2f5a011854fe5ed21d5eced038d51cb70e0ddc901d5000e34c63be9fa3b1a7c458c17e4793b40dc586520fd0818

test:
  secret_key_base: 128d5d03949a71297d1b66bcf7f80953226d9ac0ae8e872402a6097b0eea559b8f48c76ef020e318960a6b922af47b6d8f4217b51c3e14a7dc9b3f7248754ccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
